In [4]:
import pandas as pd

#读取数据
df = pd.read_csv('data/sales.csv',usecols=['订单号', '产品类别', '产品名称', '销售数量' ,'单价'])
df

#数据处理
df['销售金额'] = df['销售数量'] * df['单价']
df

#写入数据
df.to_csv('data/sales_01.csv', index = False)

In [5]:
# 数据查看--> head,tail, describe,info,shape,columns
df1 = pd.read_csv('data/sales.csv',usecols=['订单号', '产品类别', '产品名称', '销售数量' ,'单价'])

df1.head(10)#显示前10行数据
df1.tail(10)#显示后10行数据
df1.info()#显示数据信息
df1.shape#显示数据形状
df1.columns#显示数据列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [6]:
# 数据选择
df2 = pd.read_csv('data/sales.csv',usecols=['订单号', '产品类别', '产品名称', '销售数量' ,'单价'], index_col='订单号')
df2

#1. 选择列
#1.1 单列
df2['产品类别']

#1.2多列
df2[['产品类别', '产品名称']]


#2. 选择行---> loc, iloc
#2.1 iloc-->基于行号选择(不包含结束位置）。语法:df.iloc[start:stop:step]
df2.iloc[0:5]
df2.iloc[0:5:1]
df2
#2.2 loc-->基于行索引选择(包含结束位置）。语法:df.loc[start:stop:step]
df2.loc[2782973956:5027895059:1]

            产品类别  产品名称  销售数量   单价
订单号
2782973956  家居用品    枕头     3  118
3862337541    图书    漫画     2  290
9826076680    食品    牛奶     5  -78
5949577226  电子产品  蓝牙耳机     9  297
9708761103    图书    小说     9  153
3577253908    服装    T恤     8  290
9826076680  电子产品  蓝牙耳机     1   82
3971653655  家居用品    枕头    10  319
2331463704    食品    牛奶     1  376
5027895059  电子产品  蓝牙耳机     5  151

In [7]:
df3 = pd.read_csv('data/sales.csv')
#配置项，显示所有数据
# pd.set_option('display.max_rows', None)


#数据过滤 --> df[filter]
#1. 获取销售数量 >= 10
df3[df3['销售数量']>=10]

# 2. 获取产品类别为食品或图书的订单数据
df3[df3['产品类别'].isin(['食品', '图书'])]

# 3. 获取 单价在100-200之间的订单数据--->范围:between-->默认包含边界（inclusive = 'left)只包含左
df3[df3['单价'].between(100, 200)]

# 4. 获取销售数量>=8， 并且 单价>=100的订单数据---->多条件(并且:&, 或者:|)
df3[(df3['销售数量']>=8) & (df3['单价']>=100)]

# 5. 获取 产品类别为服装/食品， 支付方式为支付宝/微信支付的订单数据
df3[(df3['产品类别'].isin(['服装', '食品'])) & (df3['支付方式'].isin(['支付宝', '微信支付']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
2    9826076680   食品   牛奶     5  -78     福州  微信支付  2025-06-28
8    2331463704   食品   牛奶     1  376     北京   支付宝  2025-06-06
11   8252921620   食品   牛奶     3  131     合肥  微信支付  2025-06-25
12   1658050590   食品  巧克力     3  345     郑州   支付宝  2025-06-05
17   1728290855   服装   T恤     9  219     深圳   支付宝  2025-06-23
..          ...  ...  ...   ...  ...    ...   ...         ...
967  8741533633   食品  巧克力     5  248     武汉   支付宝  2025-06-26
973  8861165511   食品   坚果     4  170     武汉  微信支付  2025-06-16
984  4005480409   食品  巧克力     2  342     北京  微信支付  2025-06-15
986  5672595423   食品  巧克力     2  271     天津  微信支付  2025-06-16
996  9807677424   服装   T恤     2  357     天津  微信支付  2025-06-18

[208 rows x 8 columns]