In [2]:
import pandas as pd


# 1.读取数据
df = pd.read_csv('data/sales.csv', nrows=10)

# 2. 排序
# 2.1 根据销售数量倒序排序
#ascending默认True为升序，False为降序
df.sort_values('销售数量', ascending = False)

# 2.2根据单价升序排序
df.sort_values('单价', ascending = True)
# 2.3 根据单价升序排序，再根据销售数量倒序排序
df.sort_values(['单价', '销售数量'], ascending = [True, False])

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
2  9826076680    食品    牛奶     5  -78     福州  微信支付  2025-06-28
6  9826076680  电子产品  蓝牙耳机     1   82    NaN   支付宝  2025-06-07
0  2782973956  家居用品    枕头     3  118     广州   银行卡  2025-06-14
9  5027895059  电子产品  蓝牙耳机     5  151     福州   支付宝  2025-06-18
4  9708761103    图书    小说     9  153     合肥   支付宝  2025-06-14
5  3577253908    服装    T恤     8  290     合肥   银行卡  2025-06-26
1  3862337541    图书    漫画     2  290     福州  微信支付  2025-06-02
3  5949577226  电子产品  蓝牙耳机     9  297     杭州   银行卡  2025/06/07
7  3971653655  家居用品    枕头    10  319     成都  微信支付  2025-06-27
8  2331463704    食品    牛奶     1  376     北京   支付宝  2025-06-06

In [21]:
df = pd.read_csv('data/sales.csv', nrows=20)
df['销售金额'] = df['销售数量'] * df['单价']

# 3. 分组
# 3.1 根据产品类别分组， 统计各个类别的订单数量
df.groupby('产品类别')['订单号'].count()
# 3.2 根据产品类别分组， 统计各个类别的销售数量之和
df.groupby('产品类别')['销售数量'].sum()
# 3.3 根据产品类别分组， 统计各个类别的销售金额之和
df.groupby('产品类别')['销售金额'].sum()
# 3.4 根据产品类别分组， 统计各个类别的最低商品单价
df.groupby('产品类别')['单价'].min()
# 3.5 根据产品类别分组， 统计各个类别的最高商品单价
df.groupby('产品类别')['单价'].max()
# 3.6 根据产品类别分组， 统计各个类别的平均商品单价
df.groupby('产品类别')['单价'].mean()

# 3.7 根据产品类别分组， 统计各个类别的商品的平均单价、最高单价、最低单价
df.groupby('产品类别')['单价'].agg(['mean', 'max', 'min'])

# 3.8 根据产品类别分组， 统计各个类别的商品的销售数量之和，销售金额之和，平均单价
df.groupby('产品类别').agg({'销售数量': 'sum', '销售金额': 'sum', '单价': 'mean'}).round(2)

      销售数量  销售金额      单价
产品类别
图书      17  2617  175.75
家居用品    27  6816  234.80
服装      17  4291  254.50
电子产品    15  3510  176.67
食品      24  4108  203.83